# Generated by Django 3.1.6 on 2021-02-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='up_img/'),
        ),
    ]
